version: '3'
services:
  app:
    build: .
    ports:
      - "6000:6000"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crc
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    volumes:
      - db-vol:/var/lib/mysql
  
  jenkins:
    image: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    

volumes:
  - db-vol:
  - jenkins-data: