version: '3'
services:
  app_crc:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy


  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crc
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      # start_period: 30s
    volumes:
      - "db-vol:/var/lib/mysql"
      # - ${PWD}/update-db.sh:/docker-entrypoint-initdb.d/update-db.sh
      - "${PWD}/mysql:/docker-entrypoint-initdb.d"


volumes:
    db-vol:
   