version: '3'
services:
  app:
    build: .
    ports:
      - "80:5000"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crc
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    volumes:
      - db-vol:/var/lib/mysql

volumes:
  db-vol: