version: '2.2'
services:
  app_crc:
    build:
      context: .
      dockerfile: Dockerfile
    image: myimage:${TAG}
    ports:
      - "5000:5000"
    
    depends_on:
      db:
         condition: service_healthy


  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crc
    ports:
      - "3306:3306"
    healthcheck: # check the healthiness with the following configuration
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=root', '--password=root']
      interval: 3s
      timeout: 3s
      retries: 15
    volumes:
      - "db-vol:/var/lib/mysql"
      - "./mysql:/docker-entrypoint-initdb.d"


volumes:
    db-vol: